"use client";
import { useEffect, useState } from "react";
type Asset = { key: string; size: number; contentType: string; url: string | null };
export function MediaLibrary() {
  const [assets, setAssets] = useState<Asset[]>([]); const [status, setStatus] = useState("Loading media"); const [busy, setBusy] = useState(false);
  const load = async () => { const response = await fetch("/api/admin/media"); const body = await response.json().catch(() => ({})) as { data?: Asset[]; error?: string }; if (!response.ok) { setStatus(body.error ?? "Unable to load media"); return; } setAssets(body.data ?? []); setStatus("Media library"); };
  useEffect(() => { const timer = setTimeout(() => void load(), 0); return () => clearTimeout(timer); }, []);
  const upload = async (file: File) => { setBusy(true); try { const start = await fetch("/api/admin/media/uploads", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ fileName: file.name, contentType: file.type }) }); const created = await start.json() as { data?: { key: string; uploadId: string; partSize: number }; error?: string }; if (!start.ok || !created.data) throw new Error(created.error); const parts: Array<{ partNumber: number; etag: string }> = []; for (let offset = 0, n = 1; offset < file.size; offset += created.data.partSize, n += 1) { setStatus(`Uploading ${Math.round(Math.min(100, (offset + created.data.partSize) / file.size * 100))}%`); const part = await fetch(`/api/admin/media/uploads/${created.data.uploadId}?key=${encodeURIComponent(created.data.key)}&partNumber=${n}`, { method: "PUT", body: file.slice(offset, offset + created.data.partSize) }); const body = await part.json() as { data?: { etag: string }; error?: string }; if (!part.ok || !body.data) throw new Error(body.error); parts.push({ partNumber: n, etag: body.data.etag }); } const done = await fetch(`/api/admin/media/uploads/${created.data.uploadId}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ key: created.data.key, parts }) }); if (!done.ok) throw new Error("Unable to finish upload"); await load(); } catch (error) { setStatus(error instanceof Error ? error.message : "Upload failed"); } finally { setBusy(false); } };
  const remove = async (key: string) => { if (!window.confirm("Delete this media file? It cannot be restored.")) return; const response = await fetch(`/api/admin/media?key=${encodeURIComponent(key)}`, { method: "DELETE" }); if (!response.ok) { setStatus("Unable to delete media"); return; } await load(); };
  const copy = async (url: string) => { await navigator.clipboard.writeText(url); setStatus("URL copied"); };
  const place = async (key: string, placement: "showreel" | "showreel-image" | "gallery") => { const response = await fetch("/api/admin/media/placement", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ key, placement }) }); const body = await response.json().catch(() => ({})) as { error?: string }; setStatus(response.ok ? "Placement saved" : body.error ?? "Unable to save placement"); };
  return <div className="admin-editor"><section className="admin-section"><div><p className="eyebrow">R2 media</p><h2>Upload</h2><p className="admin-auth-hint">Large files upload in 8 MB parts and play directly from the public R2 domain.</p></div><div className="admin-fields"><label className="admin-field-wide"><span>Video or image</span><input type="file" accept="video/*,image/*" disabled={busy} onChange={(e) => { const file = e.target.files?.[0]; if (file) void upload(file); }} /></label><p>{status}</p></div></section><section className="admin-section"><div><p className="eyebrow">Files</p><h2>Library</h2></div><div className="admin-repeaters">{assets.map((asset) => <div className="admin-repeater-row" key={asset.key}><span>{asset.key.split("/").at(-1)} · {(asset.size / 1024 / 1024).toFixed(1)} MB</span>{asset.url ? <button type="button" onClick={() => void copy(asset.url!)}>Copy URL</button> : null}{asset.contentType.startsWith("video/") ? <button type="button" onClick={() => void place(asset.key, "showreel")}>Show on showreel</button> : <><button type="button" onClick={() => void place(asset.key, "showreel-image")}>Set reel image</button><button type="button" onClick={() => void place(asset.key, "gallery")}>Add to gallery</button></>}<button type="button" onClick={() => void remove(asset.key)}>Delete</button></div>)}</div></section></div>;
}
