"use client";

import { useState } from "react";
import { fieldValue, type EditableContent, type EditableFieldId } from "@/lib/assistant/registry";
import { RecentHighlightsEditor } from "@/components/admin/RecentHighlightsEditor";

const pageFields: Record<string, EditableFieldId[]> = { Home: ["home.heroHeading", "home.heroRole", "home.heroCopy", "home.location", "home.languages", "home.workingAcross"], Bio: ["about.heading", "about.intro", "about.body"], Contact: ["pages.contactHeading", "contact.email", "contact.phone", "contact.representation", "contact.note", "contact.formHeading"], Resume: ["pages.resumeHeading", "resume.intro", "resume.theater", "resume.stagedReadings", "resume.film", "resume.training", "resume.skills"], Video: ["pages.videoHeading", "pages.videoEmpty"], Photos: ["pages.photosHeading"], "Performance Stills": ["pages.performanceStillsHeading"], "Recent Highlights": ["pages.recentHighlightsHeading"] };
const labels: Record<string, string> = { "home.heroHeading": "Hero heading", "home.heroRole": "Role", "home.heroCopy": "Introduction", "home.location": "Location", "home.languages": "Languages", "home.workingAcross": "Working across", "about.heading": "Page heading", "about.intro": "Introduction", "about.body": "Remaining paragraphs", "contact.email": "Email", "contact.phone": "Phone", "contact.representation": "Representation", "contact.note": "Form note", "contact.formHeading": "Form heading", "resume.intro": "Introduction", "resume.theater": "Theater credits", "resume.stagedReadings": "Staged readings", "resume.film": "Film credits", "resume.training": "Training", "resume.skills": "Special skills", "pages.videoHeading": "Page heading", "pages.videoEmpty": "Empty state", "pages.contactHeading": "Page heading", "pages.resumeHeading": "Page heading", "pages.photosHeading": "Page heading", "pages.performanceStillsHeading": "Page heading", "pages.recentHighlightsHeading": "Page heading" };

export function PageEditor({ content }: { content: EditableContent }) {
  const [page, setPage] = useState("Home"); const fields = pageFields[page] ?? []; const initial = Object.fromEntries(Object.values(pageFields).flat().map((id) => [id, fieldValue(content, id)])); const [values, setValues] = useState(initial); const [baseline, setBaseline] = useState(initial); const [busy, setBusy] = useState(false); const [status, setStatus] = useState("");
  const save = async () => { const changes = fields.filter((id) => values[id] !== baseline[id]).map((fieldId) => ({ fieldId, value: values[fieldId], expectedValue: baseline[fieldId], summary: `Updated ${page} page copy`, action: "update" })); if (!changes.length) { setStatus("No unsaved changes."); return; } setBusy(true); setStatus("Saving page…"); try { const response = await fetch("/api/admin/assistant/apply", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ changes }) }); const body = await response.json().catch(() => ({})) as { error?: string; data?: { message?: string } }; if (!response.ok) { setStatus(body.error ?? "Page could not be saved."); return; } setBaseline(values); setStatus(body.data?.message ?? "Page saved."); window.dispatchEvent(new Event("assistant-history-updated")); } catch { setStatus("Page could not be saved. Check your connection and try again."); } finally { setBusy(false); } };
  return <details className="admin-collapsible admin-page-editor"><summary>Page editor</summary><div className="admin-collapsible__body"><p>Select a page to load all of its editable copy. Save changes when you are finished.</p><label className="admin-page-editor__select">Page<select value={page} onChange={(event) => setPage(event.target.value)}><option>Home</option><option>Bio</option><option>Contact</option><option>Resume</option><option>Recent Highlights</option><option>Video</option><option>Photos</option><option>Performance Stills</option></select></label>{page === "Recent Highlights" ? <><div className="admin-page-editor__fields">{fields.map((id) => <label key={id}>{labels[id]}<input value={values[id]} onChange={(event) => setValues({ ...values, [id]: event.target.value })} /></label>)}</div><button type="button" onClick={() => void save()} disabled={busy || !fields.some((id) => values[id] !== baseline[id])}>{busy ? "Saving…" : "Save page title"}</button><RecentHighlightsEditor compact /></> : fields.length ? <div className="admin-page-editor__fields">{fields.map((id) => <label key={id}>{labels[id]}{id.includes("intro") || id.endsWith("heroCopy") || id.endsWith("body") || id.startsWith("resume.") || id.startsWith("contact.representation") ? <textarea rows={id.startsWith("resume.") || id.endsWith("body") ? 10 : 5} value={values[id]} onChange={(event) => setValues({ ...values, [id]: event.target.value })} /> : <input value={values[id]} onChange={(event) => setValues({ ...values, [id]: event.target.value })} />}</label>)}</div> : null}{page !== "Recent Highlights" && fields.length ? <button type="button" onClick={() => void save()} disabled={busy || !fields.some((id) => values[id] !== baseline[id])}>{busy ? "Saving…" : "Save page"}</button> : null}{status ? <p className="admin-form-status" role="status">{status}</p> : null}</div></details>;
}
