"use client";

import { useState } from "react";
import { fieldValue, type EditableContent, type EditableFieldId } from "@/lib/assistant/registry";

const pageFields: Record<string, EditableFieldId[]> = { Home: ["home.heroHeading", "home.heroRole", "home.heroCopy"], Bio: ["about.heading", "about.intro"], Contact: ["contact.email", "contact.phone"], Resume: ["contact.email", "contact.phone"] };
const labels: Record<string, string> = { "home.heroHeading": "Hero heading", "home.heroRole": "Role", "home.heroCopy": "Introduction", "about.heading": "Page heading", "about.intro": "Introduction", "contact.email": "Email", "contact.phone": "Phone" };

export function PageEditor({ content }: { content: EditableContent }) {
  const [page, setPage] = useState("Home"); const fields = pageFields[page] ?? []; const initial = Object.fromEntries(Object.values(pageFields).flat().map((id) => [id, fieldValue(content, id)])); const [values, setValues] = useState(initial); const [baseline, setBaseline] = useState(initial); const [busy, setBusy] = useState(false); const [status, setStatus] = useState("");
  const save = async () => { const changes = fields.filter((id) => values[id] !== baseline[id]).map((fieldId) => ({ fieldId, value: values[fieldId], expectedValue: baseline[fieldId], summary: `Updated ${page} page copy`, action: "update" })); if (!changes.length) { setStatus("No unsaved changes."); return; } setBusy(true); setStatus("Saving page…"); try { const response = await fetch("/api/admin/assistant/apply", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ changes }) }); const body = await response.json().catch(() => ({})) as { error?: string; data?: { message?: string } }; if (!response.ok) { setStatus(body.error ?? "Page could not be saved."); return; } setBaseline(values); setStatus(body.data?.message ?? "Page saved."); window.dispatchEvent(new Event("assistant-history-updated")); } catch { setStatus("Page could not be saved. Check your connection and try again."); } finally { setBusy(false); } };
  return <details className="admin-collapsible admin-page-editor"><summary>Page editor</summary><div className="admin-collapsible__body"><p>Select a page to load its editable copy. Save changes when you are finished.</p><label className="admin-page-editor__select">Page<select value={page} onChange={(event) => setPage(event.target.value)}><option>Home</option><option>Bio</option><option>Contact</option><option>Resume</option><option>Recent Highlights</option><option>Video</option><option>Photos</option></select></label>{fields.length ? <div className="admin-page-editor__fields">{fields.map((id) => <label key={id}>{labels[id]}{id.includes("intro") || id.endsWith("heroCopy") ? <textarea rows={5} value={values[id]} onChange={(event) => setValues({ ...values, [id]: event.target.value })} /> : <input value={values[id]} onChange={(event) => setValues({ ...values, [id]: event.target.value })} />}</label>)}</div> : <p className="admin-page-editor__note">Use the Recent Highlights editor below for formatted content. Video and Photos media are managed in Media.</p>}{fields.length ? <button type="button" onClick={() => void save()} disabled={busy || !fields.some((id) => values[id] !== baseline[id])}>{busy ? "Saving…" : "Save page"}</button> : null}{status ? <p className="admin-form-status" role="status">{status}</p> : null}</div></details>;
}
