"use client";

import { useState } from "react";
import { APPROVED_HEADING_FONTS, fieldValue, type EditableContent, type EditableFieldId } from "@/lib/assistant/registry";

const groups = { Contact: ["contact.email", "contact.phone"], "Homepage details": ["home.heroRole", "home.location", "home.languages", "home.workingAcross"], Typography: ["theme.headingFont"], SEO: ["seo.description"] } as const;
const labels: Record<string, string> = { "contact.email": "Email", "contact.phone": "Phone", "home.heroRole": "Role", "home.location": "Location", "home.languages": "Languages", "home.workingAcross": "Working across", "theme.headingFont": "Heading font", "seo.description": "Meta description" };

export function SiteSettings({ content }: { content: EditableContent }) {
  const ids = Object.values(groups).flat() as readonly string[]; const initial = Object.fromEntries(ids.map((id) => [id, fieldValue(content, id as EditableFieldId)]));
  const [values, setValues] = useState<Record<string, string>>(initial); const [baseline, setBaseline] = useState(initial); const [busy, setBusy] = useState(false); const [status, setStatus] = useState("");
  const save = async () => { setBusy(true); setStatus("Saving settings…"); const changes = ids.filter((id) => values[id] !== baseline[id]).map((id) => ({ fieldId: id, value: values[id], expectedValue: baseline[id], summary: "Updated site settings", action: "update" })); if (!changes.length) { setBusy(false); setStatus("No unsaved settings."); return; } const response = await fetch("/api/admin/assistant/apply", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ changes }) }); const body = await response.json().catch(() => ({})) as { error?: string; data?: { message?: string } }; setBusy(false); if (!response.ok) { setStatus(body.error ?? "Settings could not be saved."); return; } setBaseline(values); setStatus(body.data?.message ?? "Settings saved."); window.dispatchEvent(new Event("assistant-history-updated")); };
  const set = (id: string, value: string) => setValues({ ...values, [id]: value });
  return <div className="admin-dashboard-section admin-settings-section"><div className="admin-section-heading"><div><p className="eyebrow">Manual controls</p><h2>Site Settings</h2><p>Manage the practical details used by the public pages. These controls do not use the AI assistant.</p></div><button type="button" onClick={() => void save()} disabled={busy || !ids.some((id) => values[id] !== baseline[id])}>{busy ? "Saving…" : "Save settings"}</button></div><div className="admin-settings-grid">{Object.entries(groups).map(([group, groupIds]) => <section className="admin-settings-group" key={group}><p className="eyebrow">{group}</p>{groupIds.map((id) => <label key={id}>{labels[id]}{id === "seo.description" ? <textarea value={values[id]} onChange={(event) => set(id, event.target.value)} maxLength={160} rows={4} /> : id === "theme.headingFont" ? <select value={values[id]} onChange={(event) => set(id, event.target.value)}>{APPROVED_HEADING_FONTS.map((font) => <option key={font}>{font}</option>)}</select> : <input value={values[id]} onChange={(event) => set(id, event.target.value)} />}</label>)}</section>)}</div>{status ? <p className="admin-form-status" role="status">{status}</p> : null}</div>;
}
